# Generated by Django 5.1.5 on 2025-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата оплаты курса или урока"
            ),
        ),
    ]
