# Generated by Django 5.1.5 on 2025-02-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses_lessons", "0002_course_owner_lesson_owner"),
        ("users", "0006_payment_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment_card",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses_lessons.course",
                verbose_name="курс",
            ),
        ),
    ]
