# Generated by Django 5.1.5 on 2025-02-05 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses_lessons", "0002_course_owner_lesson_owner"),
        ("users", "0007_payment_card_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment_card",
            new_name="PaymentCard",
        ),
    ]
